import type { Profissional } from './types'

/** Dados-semente do mock (frontend-only). Datas em ISO. */
export const SEED_PROFISSIONAIS: Profissional[] = [
  {
    id: 'seed-prof-1',
    nome: 'Fernanda Oliveira',
    email: 'fernanda.oliveira@entreser.com.br',
    telefone: '11987654321',
    crp: '06/45231',
    abordagem: 'TCC',
    ativa: true,
    convite: 'ativo',
    conviteExpiraEm: null,
    criadaEm: '2026-01-12',
    criadaPor: 'Equipe Entre Ser',
    bio: 'Psicóloga perinatal com foco em reprodução assistida.',
  },
  {
    id: 'seed-prof-2',
    nome: 'Camila Souza',
    email: 'camila.souza@entreser.com.br',
    telefone: '21991234567',
    crp: '05/33120',
    abordagem: 'ACT',
    ativa: true,
    convite: 'ativo',
    conviteExpiraEm: null,
    criadaEm: '2026-01-20',
    criadaPor: 'Equipe Entre Ser',
    bio: '',
  },
  {
    id: 'seed-prof-3',
    nome: 'Beatriz Nunes',
    email: 'beatriz.nunes@entreser.com.br',
    telefone: '31988887777',
    crp: '04/22019',
    abordagem: 'MBSR',
    ativa: true,
    convite: 'pendente',
    conviteExpiraEm: '2026-07-16',
    criadaEm: '2026-03-02',
    criadaPor: 'Equipe Entre Ser',
    bio: '',
  },
  {
    id: 'seed-prof-4',
    nome: 'Larissa Prado',
    email: 'larissa.prado@entreser.com.br',
    telefone: '11970001122',
    crp: '06/51002',
    abordagem: 'Psicanálise',
    ativa: true,
    convite: 'expirado',
    conviteExpiraEm: '2026-07-04',
    criadaEm: '2026-02-18',
    criadaPor: 'Equipe Entre Ser',
    bio: '',
  },
  {
    id: 'seed-prof-5',
    nome: 'Juliana Martins',
    email: 'juliana.martins@entreser.com.br',
    telefone: '41996553311',
    crp: '08/12876',
    abordagem: 'TCC',
    ativa: false,
    convite: 'ativo',
    conviteExpiraEm: null,
    criadaEm: '2025-12-05',
    criadaPor: 'Equipe Entre Ser',
    bio: 'Ênfase em luto gestacional.',
  },
]
