import type { Conteudo } from './types'

export const SEED_CONTEUDOS: Conteudo[] = [
  { id: 'c-1', titulo: 'Como lidar com a ansiedade na espera do beta', descricao: 'Estratégias práticas para os dias que antecedem o exame.', formato: 'artigo', publicado: true, tags: ['t-1', 't-2'], duracao: 8, corpo: 'A espera pelo resultado do beta-hCG é um dos momentos mais intensos da jornada.\n\n## Reconheça a ansiedade\n\nÉ natural sentir o coração acelerar. Nomeie o que sente sem se julgar.\n\n- Respire fundo por alguns minutos\n- Evite testar antes da data\n- Fale sobre o que sente', media: null, thumb: null, criadoEm: '2025-03-02', atualizadoEm: '2025-03-10', publicadoEm: '2025-03-05' },
  { id: 'c-2', titulo: 'Meditação guiada para a transferência', descricao: 'Áudio de relaxamento para o dia do procedimento.', formato: 'audio', publicado: true, tags: ['t-2', 't-8'], duracao: 12, corpo: '', media: 'meditacao-transferencia.mp3', thumb: null, criadoEm: '2025-02-28', atualizadoEm: '2025-02-28', publicadoEm: '2025-03-01' },
  { id: 'c-3', titulo: 'Entendendo o protocolo de estimulação', descricao: 'Vídeo explicativo sobre medicações e acompanhamento.', formato: 'video', publicado: true, tags: ['t-1', 't-3'], duracao: 15, corpo: '', media: 'protocolo-estimulacao.mp4', thumb: null, criadoEm: '2025-02-20', atualizadoEm: '2025-02-25', publicadoEm: '2025-02-22' },
  { id: 'c-4', titulo: 'Autocompaixão nos dias difíceis', descricao: 'Rascunho sobre acolher a si mesma.', formato: 'artigo', publicado: false, tags: ['t-2', 't-5'], duracao: 6, corpo: 'Rascunho em progresso…', media: null, thumb: null, criadoEm: '2025-03-15', atualizadoEm: '2025-03-16', publicadoEm: null },
  { id: 'c-5', titulo: 'Preparando o corpo: alimentação e sono', descricao: 'Nutrição e descanso na fase de preparação.', formato: 'artigo', publicado: true, tags: ['t-7', 't-8'], duracao: 10, corpo: 'Nutrição e descanso na preparação são aliados poderosos.', media: null, thumb: null, criadoEm: '2025-02-10', atualizadoEm: '2025-02-12', publicadoEm: '2025-02-11' },
  { id: 'c-6', titulo: 'Conversas com o parceiro sobre o tratamento', descricao: 'Como alinhar expectativas a dois.', formato: 'video', publicado: false, tags: ['t-4'], duracao: 18, corpo: '', media: null, thumb: null, criadoEm: '2025-03-18', atualizadoEm: '2025-03-18', publicadoEm: null },
]
